partition: gpu
gpus_per_node: 4
cpus_per_task: 32
mem_gb: 256
time_hours: 72

hydra:
  launcher:
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    partition: ${slurm.partition}
    gpus_per_node: ${slurm.gpus_per_node}
    cpus_per_task: ${slurm.cpus_per_task}
    mem_gb: ${slurm.mem_gb}
    timeout_min: 4320
    additional_parameters:
      mail-type: END,FAIL
